export const items = [
  {
    id: "02695566",
    name: "Лера",
    // image,
    date: "15 февраля 2024",
    place: "Nepal",
    generalState: "80",
    temperature: { title: "Температура", status: "good", params: "37" },
    onHead: { title: "Давление", status: "malaise", params: "90/140" },
    pressure: { title: "Наклон", status: "badly", params: "130" },
  },
  {
    id: "02695567",
    name: "Лиза",
    date: "16 февраля 2024",
    place: "Nepal",
    generalState: "30",
    // image,
    temperature: { title: "Температура", status: "good", params: "37" },
    onHead: { title: "Давление", status: "malaise", params: "90/100" },
    pressure: { title: "Наклон", status: "badly", params: "130" },
  },
  {
    id: "02695568",
    name: "Кристина",
    date: "13 февраля 2024",
    place: "Nepal",
    generalState: "20",
    // image,
    temperature: { title: "Температура", status: "good", params: "36,6" },
    onHead: { title: "Давление", status: "malaise", params: "90/100" },
    pressure: { title: "Наклон", status: "badly", params: "130" },
  },
];

export const constantsMonths = [
  "января",
  "февраля",
  "марта",
  "апреля",
  "мая",
  "июня",
  "июля",
  "августа",
  "сентября",
  "октября",
  "ноября",
  "декабря",
];
